const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  chooseFolder: () => ipcRenderer.invoke('dialog:folder'),
  confirm: message => ipcRenderer.invoke('action:confirm', message),
  getCache: () => ipcRenderer.invoke('scan:cached'),
  getConfig: () => ipcRenderer.invoke('config:get'),
  getFavorites: () => ipcRenderer.invoke('favorites:get'),
  getReview: key => ipcRenderer.invoke('review:get', key),
  onActionResult: cb => ipcRenderer.on('action:result', (_, action, cwd) => cb(action, cwd)),
  getActions: cwd => ipcRenderer.invoke('agent:actions', cwd),
  onAgentChunk: cb => ipcRenderer.on('agent:chunk', (_, chunk) => cb(chunk)),
  onAgentDone: cb => ipcRenderer.on('agent:done', (_, code) => cb(code)),
  onAgentResult: cb => ipcRenderer.on('agent:result', (_, result) => cb(result)),
  openInteractive: (prompt, cwd) => ipcRenderer.invoke('action:interactive', prompt, cwd),
  runAction: (action, cwd) => ipcRenderer.invoke('action:run', action, cwd),
  runAgent: (prompt, cwd) => ipcRenderer.invoke('agent:run', prompt, cwd),
  saveConfig: config => ipcRenderer.invoke('config:save', config),
  saveReview: (key, result) => ipcRenderer.invoke('review:save', key, result),
  getSessions: () => ipcRenderer.invoke('sessions:get'),
  scan: () => ipcRenderer.invoke('scan'),
  scanSessions: repos => ipcRenderer.invoke('sessions:scan', repos),
  serveStart: (name, cwd) => ipcRenderer.invoke('serve:start', name, cwd),
  serveStatus: cwd => ipcRenderer.invoke('serve:status', cwd),
  serveStop: cwd => ipcRenderer.invoke('serve:stop', cwd),
  setTheme: mode => ipcRenderer.invoke('theme:set', mode),
  showMenu: (actions, cwd) => ipcRenderer.invoke('action:menu', actions, cwd),
  stopAgent: () => ipcRenderer.invoke('agent:stop'),
  toggleFavorite: id => ipcRenderer.invoke('favorites:toggle', id),
})
